apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa-example-app
  labels:
    app: opa-example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa-example-app
  template:
    metadata:
      labels:
        app: opa-example-app
    spec:
      containers:
        - name: opa-example-app
          image: opa-example-app
          ports:
            - containerPort: 8080
